/*
  Simple DirectMedia Layer
  Copyright (C) 1997-2017 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

//
//  NOTICE
//
//     This file has been altered from the original
//     It contains a simplified version excluding other SDL dependencies
//

/**
 *  \file SDL_keycode.h
 *
 *  Defines constants which identify keyboard keys and modifiers.
 */

#ifndef SDL_keycode_simplified_h_
#define SDL_keycode_simplified_h_

//#include "SDL_stdinc.h"
#include "Sdl_Scancode_s.h"

#ifdef NS
namespace NS 
{
#endif // NS

 /**
  *  \brief The SDL virtual key representation.
  *
  *  Values of this type are used to represent keyboard keys using the current
  *  layout of the keyboard.  These values include Unicode values representing
  *  the unmodified character that would be generated by pressing the key, or
  *  an * constant for those keys that do not generate characters.
  *
  *  A special exception is the number keys at the top of the keyboard which
  *  always map to 0...9, regardless of layout.
  */

using Keycode = int32_t;

struct KEYCODE;

inline constexpr Scancode SCANCODE_TO_KEYCODE(Keycode X) noexcept
{
    constexpr Keycode SCANCODE_MASK = (1 << 30);
    return (X | SCANCODE_MASK);
};

struct KEYCODE
{
    using Type = Keycode;

    enum : Keycode
    {
        UNKNOWN = 0,

        RETURN = '\r',
        ESCAPE = '\033',
        BACKSPACE = '\b',
        TAB = '\t',
        SPACE = ' ',
        EXCLAIM = '!',
        QUOTEDBL = '"',
        HASH = '#',
        PERCENT = '%',
        DOLLAR = '$',
        AMPERSAND = '&',
        QUOTE = '\'',
        LEFTPAREN = '(',
        RIGHTPAREN = ')',
        ASTERISK = '*',
        PLUS = '+',
        COMMA = ',',
        MINUS = '-',
        PERIOD = '.',
        SLASH = '/',
        NUM0 = '0',
        NUM1 = '1',
        NUM2 = '2',
        NUM3 = '3',
        NUM4 = '4',
        NUM5 = '5',
        NUM6 = '6',
        NUM7 = '7',
        NUM8 = '8',
        NUM9 = '9',
        COLON = ':',
        SEMICOLON = ';',
        LESS = '<',
        EQUALS = '=',
        GREATER = '>',
        QUESTION = '?',
        AT = '@',
        /*
           Skip uppercase letters
         */
         LEFTBRACKET = '[',
         BACKSLASH = '\\',
         RIGHTBRACKET = ']',
         CARET = '^',
         UNDERSCORE = '_',
         BACKQUOTE = '`',
         a = 'a',
         b = 'b',
         c = 'c',
         d = 'd',
         e = 'e',
         f = 'f',
         g = 'g',
         h = 'h',
         i = 'i',
         j = 'j',
         k = 'k',
         l = 'l',
         m = 'm',
         n = 'n',
         o = 'o',
         p = 'p',
         q = 'q',
         r = 'r',
         s = 's',
         t = 't',
         u = 'u',
         v = 'v',
         w = 'w',
         x = 'x',
         y = 'y',
         z = 'z',

         CAPSLOCK = SCANCODE_TO_KEYCODE(SCANCODE::CAPSLOCK),

         F1 = SCANCODE_TO_KEYCODE(SCANCODE::F1),
         F2 = SCANCODE_TO_KEYCODE(SCANCODE::F2),
         F3 = SCANCODE_TO_KEYCODE(SCANCODE::F3),
         F4 = SCANCODE_TO_KEYCODE(SCANCODE::F4),
         F5 = SCANCODE_TO_KEYCODE(SCANCODE::F5),
         F6 = SCANCODE_TO_KEYCODE(SCANCODE::F6),
         F7 = SCANCODE_TO_KEYCODE(SCANCODE::F7),
         F8 = SCANCODE_TO_KEYCODE(SCANCODE::F8),
         F9 = SCANCODE_TO_KEYCODE(SCANCODE::F9),
         F10 = SCANCODE_TO_KEYCODE(SCANCODE::F10),
         F11 = SCANCODE_TO_KEYCODE(SCANCODE::F11),
         F12 = SCANCODE_TO_KEYCODE(SCANCODE::F12),

         PRINTSCREEN = SCANCODE_TO_KEYCODE(SCANCODE::PRINTSCREEN),
         SCROLLLOCK = SCANCODE_TO_KEYCODE(SCANCODE::SCROLLLOCK),
         PAUSE = SCANCODE_TO_KEYCODE(SCANCODE::PAUSE),
         INSERT = SCANCODE_TO_KEYCODE(SCANCODE::INSERT),
         HOME = SCANCODE_TO_KEYCODE(SCANCODE::HOME),
         PAGEUP = SCANCODE_TO_KEYCODE(SCANCODE::PAGEUP),
         DELETE = '\177',
         END = SCANCODE_TO_KEYCODE(SCANCODE::END),
         PAGEDOWN = SCANCODE_TO_KEYCODE(SCANCODE::PAGEDOWN),
         RIGHT = SCANCODE_TO_KEYCODE(SCANCODE::RIGHT),
         LEFT = SCANCODE_TO_KEYCODE(SCANCODE::LEFT),
         DOWN = SCANCODE_TO_KEYCODE(SCANCODE::DOWN),
         UP = SCANCODE_TO_KEYCODE(SCANCODE::UP),

         NUMLOCKCLEAR = SCANCODE_TO_KEYCODE(SCANCODE::NUMLOCKCLEAR),
         KP_DIVIDE = SCANCODE_TO_KEYCODE(SCANCODE::KP_DIVIDE),
         KP_MULTIPLY = SCANCODE_TO_KEYCODE(SCANCODE::KP_MULTIPLY),
         KP_MINUS = SCANCODE_TO_KEYCODE(SCANCODE::KP_MINUS),
         KP_PLUS = SCANCODE_TO_KEYCODE(SCANCODE::KP_PLUS),
         KP_ENTER = SCANCODE_TO_KEYCODE(SCANCODE::KP_ENTER),
         KP_1 = SCANCODE_TO_KEYCODE(SCANCODE::KP_1),
         KP_2 = SCANCODE_TO_KEYCODE(SCANCODE::KP_2),
         KP_3 = SCANCODE_TO_KEYCODE(SCANCODE::KP_3),
         KP_4 = SCANCODE_TO_KEYCODE(SCANCODE::KP_4),
         KP_5 = SCANCODE_TO_KEYCODE(SCANCODE::KP_5),
         KP_6 = SCANCODE_TO_KEYCODE(SCANCODE::KP_6),
         KP_7 = SCANCODE_TO_KEYCODE(SCANCODE::KP_7),
         KP_8 = SCANCODE_TO_KEYCODE(SCANCODE::KP_8),
         KP_9 = SCANCODE_TO_KEYCODE(SCANCODE::KP_9),
         KP_0 = SCANCODE_TO_KEYCODE(SCANCODE::KP_0),
         KP_PERIOD = SCANCODE_TO_KEYCODE(SCANCODE::KP_PERIOD),

         APPLICATION = SCANCODE_TO_KEYCODE(SCANCODE::APPLICATION),
         POWER = SCANCODE_TO_KEYCODE(SCANCODE::POWER),
         KP_EQUALS = SCANCODE_TO_KEYCODE(SCANCODE::KP_EQUALS),
         F13 = SCANCODE_TO_KEYCODE(SCANCODE::F13),
         F14 = SCANCODE_TO_KEYCODE(SCANCODE::F14),
         F15 = SCANCODE_TO_KEYCODE(SCANCODE::F15),
         F16 = SCANCODE_TO_KEYCODE(SCANCODE::F16),
         F17 = SCANCODE_TO_KEYCODE(SCANCODE::F17),
         F18 = SCANCODE_TO_KEYCODE(SCANCODE::F18),
         F19 = SCANCODE_TO_KEYCODE(SCANCODE::F19),
         F20 = SCANCODE_TO_KEYCODE(SCANCODE::F20),
         F21 = SCANCODE_TO_KEYCODE(SCANCODE::F21),
         F22 = SCANCODE_TO_KEYCODE(SCANCODE::F22),
         F23 = SCANCODE_TO_KEYCODE(SCANCODE::F23),
         F24 = SCANCODE_TO_KEYCODE(SCANCODE::F24),
         EXECUTE = SCANCODE_TO_KEYCODE(SCANCODE::EXECUTE),
         HELP = SCANCODE_TO_KEYCODE(SCANCODE::HELP),
         MENU = SCANCODE_TO_KEYCODE(SCANCODE::MENU),
         SELECT = SCANCODE_TO_KEYCODE(SCANCODE::SELECT),
         STOP = SCANCODE_TO_KEYCODE(SCANCODE::STOP),
         AGAIN = SCANCODE_TO_KEYCODE(SCANCODE::AGAIN),
         UNDO = SCANCODE_TO_KEYCODE(SCANCODE::UNDO),
         CUT = SCANCODE_TO_KEYCODE(SCANCODE::CUT),
         COPY = SCANCODE_TO_KEYCODE(SCANCODE::COPY),
         PASTE = SCANCODE_TO_KEYCODE(SCANCODE::PASTE),
         FIND = SCANCODE_TO_KEYCODE(SCANCODE::FIND),
         MUTE = SCANCODE_TO_KEYCODE(SCANCODE::MUTE),
         VOLUMEUP = SCANCODE_TO_KEYCODE(SCANCODE::VOLUMEUP),
         VOLUMEDOWN = SCANCODE_TO_KEYCODE(SCANCODE::VOLUMEDOWN),
         KP_COMMA = SCANCODE_TO_KEYCODE(SCANCODE::KP_COMMA),
         KP_EQUALSAS400 =
         SCANCODE_TO_KEYCODE(SCANCODE::KP_EQUALSAS400),

        ALTERASE = SCANCODE_TO_KEYCODE(SCANCODE::ALTERASE),
        SYSREQ = SCANCODE_TO_KEYCODE(SCANCODE::SYSREQ),
        CANCEL = SCANCODE_TO_KEYCODE(SCANCODE::CANCEL),
        CLEAR = SCANCODE_TO_KEYCODE(SCANCODE::CLEAR),
        PRIOR = SCANCODE_TO_KEYCODE(SCANCODE::PRIOR),
        RETURN2 = SCANCODE_TO_KEYCODE(SCANCODE::RETURN2),
        SEPARATOR = SCANCODE_TO_KEYCODE(SCANCODE::SEPARATOR),
        OUT = SCANCODE_TO_KEYCODE(SCANCODE::OUT),
        OPER = SCANCODE_TO_KEYCODE(SCANCODE::OPER),
        CLEARAGAIN = SCANCODE_TO_KEYCODE(SCANCODE::CLEARAGAIN),
        CRSEL = SCANCODE_TO_KEYCODE(SCANCODE::CRSEL),
        EXSEL = SCANCODE_TO_KEYCODE(SCANCODE::EXSEL),

        KP_00 = SCANCODE_TO_KEYCODE(SCANCODE::KP_00),
        KP_000 = SCANCODE_TO_KEYCODE(SCANCODE::KP_000),
        THOUSANDSSEPARATOR =
        SCANCODE_TO_KEYCODE(SCANCODE::THOUSANDSSEPARATOR),
        DECIMALSEPARATOR =
        SCANCODE_TO_KEYCODE(SCANCODE::DECIMALSEPARATOR),
        CURRENCYUNIT = SCANCODE_TO_KEYCODE(SCANCODE::CURRENCYUNIT),
        CURRENCYSUBUNIT =
        SCANCODE_TO_KEYCODE(SCANCODE::CURRENCYSUBUNIT),
        KP_LEFTPAREN = SCANCODE_TO_KEYCODE(SCANCODE::KP_LEFTPAREN),
        KP_RIGHTPAREN = SCANCODE_TO_KEYCODE(SCANCODE::KP_RIGHTPAREN),
        KP_LEFTBRACE = SCANCODE_TO_KEYCODE(SCANCODE::KP_LEFTBRACE),
        KP_RIGHTBRACE = SCANCODE_TO_KEYCODE(SCANCODE::KP_RIGHTBRACE),
        KP_TAB = SCANCODE_TO_KEYCODE(SCANCODE::KP_TAB),
        KP_BACKSPACE = SCANCODE_TO_KEYCODE(SCANCODE::KP_BACKSPACE),
        KP_A = SCANCODE_TO_KEYCODE(SCANCODE::KP_A),
        KP_B = SCANCODE_TO_KEYCODE(SCANCODE::KP_B),
        KP_C = SCANCODE_TO_KEYCODE(SCANCODE::KP_C),
        KP_D = SCANCODE_TO_KEYCODE(SCANCODE::KP_D),
        KP_E = SCANCODE_TO_KEYCODE(SCANCODE::KP_E),
        KP_F = SCANCODE_TO_KEYCODE(SCANCODE::KP_F),
        KP_XOR = SCANCODE_TO_KEYCODE(SCANCODE::KP_XOR),
        KP_POWER = SCANCODE_TO_KEYCODE(SCANCODE::KP_POWER),
        KP_PERCENT = SCANCODE_TO_KEYCODE(SCANCODE::KP_PERCENT),
        KP_LESS = SCANCODE_TO_KEYCODE(SCANCODE::KP_LESS),
        KP_GREATER = SCANCODE_TO_KEYCODE(SCANCODE::KP_GREATER),
        KP_AMPERSAND = SCANCODE_TO_KEYCODE(SCANCODE::KP_AMPERSAND),
        KP_DBLAMPERSAND =
        SCANCODE_TO_KEYCODE(SCANCODE::KP_DBLAMPERSAND),
        KP_VERTICALBAR =
        SCANCODE_TO_KEYCODE(SCANCODE::KP_VERTICALBAR),
        KP_DBLVERTICALBAR =
        SCANCODE_TO_KEYCODE(SCANCODE::KP_DBLVERTICALBAR),
        KP_COLON = SCANCODE_TO_KEYCODE(SCANCODE::KP_COLON),
        KP_HASH = SCANCODE_TO_KEYCODE(SCANCODE::KP_HASH),
        KP_SPACE = SCANCODE_TO_KEYCODE(SCANCODE::KP_SPACE),
        KP_AT = SCANCODE_TO_KEYCODE(SCANCODE::KP_AT),
        KP_EXCLAM = SCANCODE_TO_KEYCODE(SCANCODE::KP_EXCLAM),
        KP_MEMSTORE = SCANCODE_TO_KEYCODE(SCANCODE::KP_MEMSTORE),
        KP_MEMRECALL = SCANCODE_TO_KEYCODE(SCANCODE::KP_MEMRECALL),
        KP_MEMCLEAR = SCANCODE_TO_KEYCODE(SCANCODE::KP_MEMCLEAR),
        KP_MEMADD = SCANCODE_TO_KEYCODE(SCANCODE::KP_MEMADD),
        KP_MEMSUBTRACT =
        SCANCODE_TO_KEYCODE(SCANCODE::KP_MEMSUBTRACT),
        KP_MEMMULTIPLY =
        SCANCODE_TO_KEYCODE(SCANCODE::KP_MEMMULTIPLY),
        KP_MEMDIVIDE = SCANCODE_TO_KEYCODE(SCANCODE::KP_MEMDIVIDE),
        KP_PLUSMINUS = SCANCODE_TO_KEYCODE(SCANCODE::KP_PLUSMINUS),
        KP_CLEAR = SCANCODE_TO_KEYCODE(SCANCODE::KP_CLEAR),
        KP_CLEARENTRY = SCANCODE_TO_KEYCODE(SCANCODE::KP_CLEARENTRY),
        KP_BINARY = SCANCODE_TO_KEYCODE(SCANCODE::KP_BINARY),
        KP_OCTAL = SCANCODE_TO_KEYCODE(SCANCODE::KP_OCTAL),
        KP_DECIMAL = SCANCODE_TO_KEYCODE(SCANCODE::KP_DECIMAL),
        KP_HEXADECIMAL =
        SCANCODE_TO_KEYCODE(SCANCODE::KP_HEXADECIMAL),

        LCTRL = SCANCODE_TO_KEYCODE(SCANCODE::LCTRL),
        LSHIFT = SCANCODE_TO_KEYCODE(SCANCODE::LSHIFT),
        LALT = SCANCODE_TO_KEYCODE(SCANCODE::LALT),
        LGUI = SCANCODE_TO_KEYCODE(SCANCODE::LGUI),
        RCTRL = SCANCODE_TO_KEYCODE(SCANCODE::RCTRL),
        RSHIFT = SCANCODE_TO_KEYCODE(SCANCODE::RSHIFT),
        RALT = SCANCODE_TO_KEYCODE(SCANCODE::RALT),
        RGUI = SCANCODE_TO_KEYCODE(SCANCODE::RGUI),

        MODE = SCANCODE_TO_KEYCODE(SCANCODE::MODE),

        AUDIONEXT = SCANCODE_TO_KEYCODE(SCANCODE::AUDIONEXT),
        AUDIOPREV = SCANCODE_TO_KEYCODE(SCANCODE::AUDIOPREV),
        AUDIOSTOP = SCANCODE_TO_KEYCODE(SCANCODE::AUDIOSTOP),
        AUDIOPLAY = SCANCODE_TO_KEYCODE(SCANCODE::AUDIOPLAY),
        AUDIOMUTE = SCANCODE_TO_KEYCODE(SCANCODE::AUDIOMUTE),
        MEDIASELECT = SCANCODE_TO_KEYCODE(SCANCODE::MEDIASELECT),
        WWW = SCANCODE_TO_KEYCODE(SCANCODE::WWW),
        MAIL = SCANCODE_TO_KEYCODE(SCANCODE::MAIL),
        CALCULATOR = SCANCODE_TO_KEYCODE(SCANCODE::CALCULATOR),
        COMPUTER = SCANCODE_TO_KEYCODE(SCANCODE::COMPUTER),
        AC_SEARCH = SCANCODE_TO_KEYCODE(SCANCODE::AC_SEARCH),
        AC_HOME = SCANCODE_TO_KEYCODE(SCANCODE::AC_HOME),
        AC_BACK = SCANCODE_TO_KEYCODE(SCANCODE::AC_BACK),
        AC_FORWARD = SCANCODE_TO_KEYCODE(SCANCODE::AC_FORWARD),
        AC_STOP = SCANCODE_TO_KEYCODE(SCANCODE::AC_STOP),
        AC_REFRESH = SCANCODE_TO_KEYCODE(SCANCODE::AC_REFRESH),
        AC_BOOKMARKS = SCANCODE_TO_KEYCODE(SCANCODE::AC_BOOKMARKS),

        BRIGHTNESSDOWN =
        SCANCODE_TO_KEYCODE(SCANCODE::BRIGHTNESSDOWN),
        BRIGHTNESSUP = SCANCODE_TO_KEYCODE(SCANCODE::BRIGHTNESSUP),
        DISPLAYSWITCH = SCANCODE_TO_KEYCODE(SCANCODE::DISPLAYSWITCH),
        KBDILLUMTOGGLE =
        SCANCODE_TO_KEYCODE(SCANCODE::KBDILLUMTOGGLE),
        KBDILLUMDOWN = SCANCODE_TO_KEYCODE(SCANCODE::KBDILLUMDOWN),
        KBDILLUMUP = SCANCODE_TO_KEYCODE(SCANCODE::KBDILLUMUP),
        EJECT = SCANCODE_TO_KEYCODE(SCANCODE::EJECT),
        SLEEP = SCANCODE_TO_KEYCODE(SCANCODE::SLEEP),
        APP1 = SCANCODE_TO_KEYCODE(SCANCODE::APP1),
        APP2 = SCANCODE_TO_KEYCODE(SCANCODE::APP2),

        AUDIOREWIND = SCANCODE_TO_KEYCODE(SCANCODE::AUDIOREWIND),
        AUDIOFASTFORWARD = SCANCODE_TO_KEYCODE(SCANCODE::AUDIOFASTFORWARD)
    };

};

using Keymod = int32_t;

struct KEYMOD
{

    using Type = Keymod;

    /**
     * \brief Enumeration of valid key mods (possibly OR'd together).
     */
    enum : Keymod
    {
        KMOD_NONE = 0x0000,
        KMOD_LSHIFT = 0x0001,
        KMOD_RSHIFT = 0x0002,
        KMOD_LCTRL = 0x0040,
        KMOD_RCTRL = 0x0080,
        KMOD_LALT = 0x0100,
        KMOD_RALT = 0x0200,
        KMOD_LGUI = 0x0400,
        KMOD_RGUI = 0x0800,
        KMOD_NUM = 0x1000,
        KMOD_CAPS = 0x2000,
        KMOD_MODE = 0x4000,
        KMOD_RESERVED = 0x8000,

        KMOD_CTRL = (KMOD_LCTRL | KMOD_RCTRL),
        KMOD_SHIFT = (KMOD_LSHIFT | KMOD_RSHIFT),
        KMOD_ALT = (KMOD_LALT | KMOD_RALT),
        KMOD_GUI = (KMOD_LGUI | KMOD_RGUI),
    };

};

#endif /* SDL_keycode_simplified_h_ */

#ifdef NS
} // namespace NS
#endif
